/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Dagger_1: THREE.Mesh
    Dagger_2: THREE.Mesh
    Dagger_3: THREE.Mesh
    Dagger_4: THREE.Mesh
    Dagger_5: THREE.Mesh
  }
  materials: {
    DarkSteel: THREE.MeshStandardMaterial
    DarkWood: THREE.MeshStandardMaterial
    LightWood: THREE.MeshStandardMaterial
    LightSteel: THREE.MeshStandardMaterial
    Steel: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/Dagger.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.Dagger_1.geometry} material={materials.DarkSteel} />
        <mesh geometry={nodes.Dagger_2.geometry} material={materials.DarkWood} />
        <mesh geometry={nodes.Dagger_3.geometry} material={materials.LightWood} />
        <mesh geometry={nodes.Dagger_4.geometry} material={materials.LightSteel} />
        <mesh geometry={nodes.Dagger_5.geometry} material={materials.Steel} />
      </group>
    </group>
  )
}

useGLTF.preload('/Dagger.glb')
