import dynamic from 'next/dynamic'

export const Arrow = dynamic(() => import('./Arrow'), { ssr: false })
export const Axe = dynamic(() => import('./Axe'), { ssr: false })
export const Axe_Double = dynamic(() => import('./Axe_Double'), { ssr: false })
export const Axe_Small = dynamic(() => import('./Axe_Small'), { ssr: false })
export const Bow_Evil = dynamic(() => import('./Bow_Evil'), { ssr: false })
export const Bow_Golden = dynamic(() => import('./Bow_Golden'), { ssr: false })
export const Bow_Wooden = dynamic(() => import('./Bow_Wooden'), { ssr: false })
export const Bow_Wooden2 = dynamic(() => import('./Bow_Wooden2'), { ssr: false })
export const Claymore = dynamic(() => import('./Claymore'), { ssr: false })
export const Dagger = dynamic(() => import('./Dagger'), { ssr: false })
export const Dagger_2 = dynamic(() => import('./Dagger_2'), { ssr: false })
export const Hammer_Double = dynamic(() => import('./Hammer_Double'), { ssr: false })
export const Hammer_Small = dynamic(() => import('./Hammer_Small'), { ssr: false })
export const Scythe = dynamic(() => import('./Scythe'), { ssr: false })
export const Shield_Celtic_Golden = dynamic(() => import('./Shield_Celtic_Golden'), { ssr: false })
export const Shield_Heater = dynamic(() => import('./Shield_Heater'), { ssr: false })
export const Shield_Heater_2 = dynamic(() => import('./Shield_Heater_2'), { ssr: false })
export const Shield_Round = dynamic(() => import('./Shield_Round'), { ssr: false })
export const Shield_Round_2 = dynamic(() => import('./Shield_Round_2'), { ssr: false })
export const Spear = dynamic(() => import('./Spear'), { ssr: false })
export const Sword = dynamic(() => import('./Sword'), { ssr: false })
export const Sword_2 = dynamic(() => import('./Sword_2'), { ssr: false })
export const Sword_Big = dynamic(() => import('./Sword_Big'), { ssr: false })
export const Sword_Golden = dynamic(() => import('./Sword_Golden'), { ssr: false })
