/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Shield_Celtic_Golden_1: THREE.Mesh
    Shield_Celtic_Golden_2: THREE.Mesh
    Shield_Celtic_Golden_3: THREE.Mesh
    Shield_Celtic_Golden_4: THREE.Mesh
  }
  materials: {
    Gold: THREE.MeshStandardMaterial
    LightBlue: THREE.MeshStandardMaterial
    Green: THREE.MeshStandardMaterial
    LightGold: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/Shield_Celtic_Golden.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.Shield_Celtic_Golden_1.geometry} material={materials.Gold} />
        <mesh geometry={nodes.Shield_Celtic_Golden_2.geometry} material={materials.LightBlue} />
        <mesh geometry={nodes.Shield_Celtic_Golden_3.geometry} material={materials.Green} />
        <mesh geometry={nodes.Shield_Celtic_Golden_4.geometry} material={materials.LightGold} />
      </group>
    </group>
  )
}

useGLTF.preload('/Shield_Celtic_Golden.glb')
