import dynamic from 'next/dynamic'

export const A1Story_GableRoof_Mat = dynamic(() => import('./A1Story_GableRoof_Mat'), { ssr: false })
export const A1Story_Mat = dynamic(() => import('./A1Story_Mat'), { ssr: false })
export const A1Story_RoundRoof_Mat = dynamic(() => import('./A1Story_RoundRoof_Mat'), { ssr: false })
export const A1Story_Sign_Mat = dynamic(() => import('./A1Story_Sign_Mat'), { ssr: false })
export const A2Story_2_Mat = dynamic(() => import('./A2Story_2_Mat'), { ssr: false })
export const A2Story_Balcony_Mat = dynamic(() => import('./A2Story_Balcony_Mat'), { ssr: false })
export const A2Story_Center_Mat = dynamic(() => import('./A2Story_Center_Mat'), { ssr: false })
export const A2Story_Columns_Mat = dynamic(() => import('./A2Story_Columns_Mat'), { ssr: false })
export const A2Story_Double_Mat = dynamic(() => import('./A2Story_Double_Mat'), { ssr: false })
export const A2Story_GableRoof_Mat = dynamic(() => import('./A2Story_GableRoof_Mat'), { ssr: false })
export const A2Story_Mat = dynamic(() => import('./A2Story_Mat'), { ssr: false })
export const A2Story_RoundRoof_Mat = dynamic(() => import('./A2Story_RoundRoof_Mat'), { ssr: false })
export const A2Story_Sidehouse_Mat = dynamic(() => import('./A2Story_Sidehouse_Mat'), { ssr: false })
export const A2Story_Sign_Mat = dynamic(() => import('./A2Story_Sign_Mat'), { ssr: false })
export const A2Story_Slim_Mat = dynamic(() => import('./A2Story_Slim_Mat'), { ssr: false })
export const A2Story_Stairs_Mat = dynamic(() => import('./A2Story_Stairs_Mat'), { ssr: false })
export const A2Story_Wide_2Doors_Mat = dynamic(() => import('./A2Story_Wide_2Doors_Mat'), { ssr: false })
export const A2Story_Wide_Mat = dynamic(() => import('./A2Story_Wide_Mat'), { ssr: false })
export const A3Story_Balcony_Mat = dynamic(() => import('./A3Story_Balcony_Mat'), { ssr: false })
export const A3Story_Slim_Mat = dynamic(() => import('./A3Story_Slim_Mat'), { ssr: false })
export const A3Story_Small_Mat = dynamic(() => import('./A3Story_Small_Mat'), { ssr: false })
export const A4Story_Center_Mat = dynamic(() => import('./A4Story_Center_Mat'), { ssr: false })
export const A4Story_Mat = dynamic(() => import('./A4Story_Mat'), { ssr: false })
export const A4Story_Wide_2Doors_Mat = dynamic(() => import('./A4Story_Wide_2Doors_Mat'), { ssr: false })
export const A4Story_Wide_2Doors_Roof_Mat = dynamic(() => import('./A4Story_Wide_2Doors_Roof_Mat'), { ssr: false })
export const A6Story_Stack_Mat = dynamic(() => import('./A6Story_Stack_Mat'), { ssr: false })