/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    BackWheels_Cylinder007: THREE.Mesh
    ['SchoolBus_Cube001-Mesh']: THREE.Mesh
    ['SchoolBus_Cube001-Mesh_1']: THREE.Mesh
    ['SchoolBus_Cube001-Mesh_2']: THREE.Mesh
    ['SchoolBus_Cube001-Mesh_3']: THREE.Mesh
    ['SchoolBus_Cube001-Mesh_4']: THREE.Mesh
    FrontWheels_Cylinder006: THREE.Mesh
  }
  materials: {
    Wheel: THREE.MeshStandardMaterial
    Yellow: THREE.MeshStandardMaterial
    Windows: THREE.MeshStandardMaterial
    Details: THREE.MeshStandardMaterial
    Bumper: THREE.MeshStandardMaterial
    Lights: THREE.MeshStandardMaterial
  }
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/glb/public_transport_pack/SchoolBus.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.BackWheels_Cylinder007.geometry} material={materials.Wheel} />
      <mesh geometry={nodes['SchoolBus_Cube001-Mesh'].geometry} material={materials.Yellow} />
      <mesh geometry={nodes['SchoolBus_Cube001-Mesh_1'].geometry} material={materials.Windows} />
      <mesh geometry={nodes['SchoolBus_Cube001-Mesh_2'].geometry} material={materials.Details} />
      <mesh geometry={nodes['SchoolBus_Cube001-Mesh_3'].geometry} material={materials.Bumper} />
      <mesh geometry={nodes['SchoolBus_Cube001-Mesh_4'].geometry} material={materials.Lights} />
      <mesh geometry={nodes.FrontWheels_Cylinder006.geometry} material={materials.Wheel} />
    </group>
  )
}

useGLTF.preload('/glb/public_transport_pack/SchoolBus.glb')
