/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cone_1: THREE.Mesh
    Cone_2: THREE.Mesh
  }
  materials: {
    Orange: THREE.MeshStandardMaterial
    White: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/TrafficCone.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={42.43}>
        <mesh geometry={nodes.Cone_1.geometry} material={materials.Orange} />
        <mesh geometry={nodes.Cone_2.geometry} material={materials.White} />
      </group>
    </group>
  )
}

useGLTF.preload('/TrafficCone.glb')
