/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    ['TrafficLight_Cube001-Mesh']: THREE.Mesh
    ['TrafficLight_Cube001-Mesh_1']: THREE.Mesh
    ['TrafficLight_Cube001-Mesh_2']: THREE.Mesh
    ['TrafficLight_Cube001-Mesh_3']: THREE.Mesh
  }
  materials: {
    TrafficLight: THREE.MeshStandardMaterial
    Green: THREE.MeshStandardMaterial
    Yellow: THREE.MeshStandardMaterial
    Red: THREE.MeshStandardMaterial
  }
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/glb/public_transport_pack/TrafficLight.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['TrafficLight_Cube001-Mesh'].geometry} material={materials.TrafficLight} />
      <mesh geometry={nodes['TrafficLight_Cube001-Mesh_1'].geometry} material={materials.Green} />
      <mesh geometry={nodes['TrafficLight_Cube001-Mesh_2'].geometry} material={materials.Yellow} />
      <mesh geometry={nodes['TrafficLight_Cube001-Mesh_3'].geometry} material={materials.Red} />
    </group>
  )
}

useGLTF.preload('/glb/public_transport_pack/TrafficLight.glb')
