/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    ['Cone_Cone001-Mesh']: THREE.Mesh
    ['Cone_Cone001-Mesh_1']: THREE.Mesh
  }
  materials: {
    Orange: THREE.MeshStandardMaterial
    White: THREE.MeshStandardMaterial
  }
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/glb/public_transport_pack/TrafficCone.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['Cone_Cone001-Mesh'].geometry} material={materials.Orange} />
      <mesh geometry={nodes['Cone_Cone001-Mesh_1'].geometry} material={materials.White} />
    </group>
  )
}

useGLTF.preload('/glb/public_transport_pack/TrafficCone.glb')
