/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Bookcase_Full_1: THREE.Mesh
    Bookcase_Full_2: THREE.Mesh
    Bookcase_Full_3: THREE.Mesh
    Bookcase_Full_4: THREE.Mesh
    Bookcase_Full_5: THREE.Mesh
    Bookcase_Full_6: THREE.Mesh
    Bookcase_Full_7: THREE.Mesh
  }
  materials: {
    Wood: THREE.MeshStandardMaterial
    DarkWood: THREE.MeshStandardMaterial
    Book2: THREE.MeshStandardMaterial
    Pages: THREE.MeshStandardMaterial
    Book4: THREE.MeshStandardMaterial
    Book3: THREE.MeshStandardMaterial
    Book: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/glb/Bookcase_Full.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.Bookcase_Full_1.geometry} material={materials.Wood} />
        <mesh geometry={nodes.Bookcase_Full_2.geometry} material={materials.DarkWood} />
        <mesh geometry={nodes.Bookcase_Full_3.geometry} material={materials.Book2} />
        <mesh geometry={nodes.Bookcase_Full_4.geometry} material={materials.Pages} />
        <mesh geometry={nodes.Bookcase_Full_5.geometry} material={materials.Book4} />
        <mesh geometry={nodes.Bookcase_Full_6.geometry} material={materials.Book3} />
        <mesh geometry={nodes.Bookcase_Full_7.geometry} material={materials.Book} />
      </group>
    </group>
  )
}

useGLTF.preload('/Bookcase_Full.glb')
