/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Pumpkin_4_1: THREE.Mesh
    Pumpkin_4_2: THREE.Mesh
    Pumpkin_4_3: THREE.Mesh
  }
  materials: {
    Orange: THREE.MeshStandardMaterial
    Green: THREE.MeshStandardMaterial
    DarkGreen: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/glb/Pumpkin_4.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.Pumpkin_4_1.geometry} material={materials.Orange} />
        <mesh geometry={nodes.Pumpkin_4_2.geometry} material={materials.Green} />
        <mesh geometry={nodes.Pumpkin_4_3.geometry} material={materials.DarkGreen} />
      </group>
    </group>
  )
}
