/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Column_Slim_1: THREE.Mesh
    Column_Slim_2: THREE.Mesh
    Column_Slim_3: THREE.Mesh
  }
  materials: {
    DarkGrey: THREE.MeshStandardMaterial
    Pipes: THREE.MeshStandardMaterial
    Main: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/Column_Slim.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.Column_Slim_1.geometry} material={materials.DarkGrey} />
        <mesh geometry={nodes.Column_Slim_2.geometry} material={materials.Pipes} />
        <mesh geometry={nodes.Column_Slim_3.geometry} material={materials.Main} />
      </group>
    </group>
  )
}

useGLTF.preload('/Column_Slim.glb')
