/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Props_ChestBottom_1: THREE.Mesh
    Props_ChestBottom_2: THREE.Mesh
    Props_ChestBottom_3: THREE.Mesh
    Props_ChestBottom_4: THREE.Mesh
    Props_ChestBottom_5: THREE.Mesh
    Props_ChestTop_1: THREE.Mesh
    Props_ChestTop_2: THREE.Mesh
    Props_ChestTop_3: THREE.Mesh
    Props_ChestTop_4: THREE.Mesh
    Props_ChestTop_5: THREE.Mesh
  }
  materials: {
    Main: THREE.MeshStandardMaterial
    Accent: THREE.MeshStandardMaterial
    DarkGrey: THREE.MeshStandardMaterial
    Black: THREE.MeshStandardMaterial
    DarkAccent: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/Props_Chest.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.Props_ChestBottom_1.geometry} material={materials.Main} />
        <mesh geometry={nodes.Props_ChestBottom_2.geometry} material={materials.Accent} />
        <mesh geometry={nodes.Props_ChestBottom_3.geometry} material={materials.DarkGrey} />
        <mesh geometry={nodes.Props_ChestBottom_4.geometry} material={materials.Black} />
        <mesh geometry={nodes.Props_ChestBottom_5.geometry} material={materials.DarkAccent} />
      </group>
      <group position={[0, 0.6, -0.37]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.Props_ChestTop_1.geometry} material={materials.Main} />
        <mesh geometry={nodes.Props_ChestTop_2.geometry} material={materials.Accent} />
        <mesh geometry={nodes.Props_ChestTop_3.geometry} material={materials.DarkGrey} />
        <mesh geometry={nodes.Props_ChestTop_4.geometry} material={materials.Black} />
        <mesh geometry={nodes.Props_ChestTop_5.geometry} material={materials.DarkAccent} />
      </group>
    </group>
  )
}

useGLTF.preload('/Props_Chest.glb')
