/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import type * as THREE from "three";
import type { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    CactusFlowers_5_1: THREE.Mesh;
    CactusFlowers_5_2: THREE.Mesh;
  };
  materials: {
    Pink: THREE.MeshStandardMaterial;
    Green: THREE.MeshStandardMaterial;
  };
};

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/glb/nature_pack/CactusFlowers_5.glb",
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.CactusFlowers_5_1.geometry} material={materials.Pink} />
        <mesh geometry={nodes.CactusFlowers_5_2.geometry} material={materials.Green} />
      </group>
    </group>
  );
}
