/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Lilypad_1: THREE.Mesh
    Lilypad_2: THREE.Mesh
  }
  materials: {
    Green: THREE.MeshStandardMaterial
    Pink: THREE.MeshStandardMaterial
  }
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/glb/nature_pack/Lilypad.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.Lilypad_1.geometry} material={materials.Green} />
        <mesh geometry={nodes.Lilypad_2.geometry} material={materials.Pink} />
      </group>
    </group>
  )
}
