/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Arrow_Golden_1: THREE.Mesh
    Arrow_Golden_2: THREE.Mesh
  }
  materials: {
    Golden: THREE.MeshStandardMaterial
    LightWood: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/Arrow_Golden.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.Arrow_Golden_1.geometry} material={materials.Golden} />
        <mesh geometry={nodes.Arrow_Golden_2.geometry} material={materials.LightWood} />
      </group>
    </group>
  )
}

useGLTF.preload('/Arrow_Golden.glb')
