/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Axe_small_1: THREE.Mesh
    Axe_small_2: THREE.Mesh
    Axe_small_3: THREE.Mesh
    Axe_small_4: THREE.Mesh
  }
  materials: {
    DarkWood: THREE.MeshStandardMaterial
    LightWood: THREE.MeshStandardMaterial
    Steel: THREE.MeshStandardMaterial
    LightSteel: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/Axe_small.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.Axe_small_1.geometry} material={materials.DarkWood} />
        <mesh geometry={nodes.Axe_small_2.geometry} material={materials.LightWood} />
        <mesh geometry={nodes.Axe_small_3.geometry} material={materials.Steel} />
        <mesh geometry={nodes.Axe_small_4.geometry} material={materials.LightSteel} />
      </group>
    </group>
  )
}

useGLTF.preload('/Axe_small.glb')
