/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Book4_Closed_1: THREE.Mesh
    Book4_Closed_2: THREE.Mesh
    Book4_Closed_3: THREE.Mesh
    Book4_Closed_4: THREE.Mesh
  }
  materials: {
    Teal: THREE.MeshStandardMaterial
    Beige: THREE.MeshStandardMaterial
    DarkTeal: THREE.MeshStandardMaterial
    DarkRed: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/glb/Book4_Closed.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.Book4_Closed_1.geometry} material={materials.Teal} />
        <mesh geometry={nodes.Book4_Closed_2.geometry} material={materials.Beige} />
        <mesh geometry={nodes.Book4_Closed_3.geometry} material={materials.DarkTeal} />
        <mesh geometry={nodes.Book4_Closed_4.geometry} material={materials.DarkRed} />
      </group>
    </group>
  )
}

useGLTF.preload('/Book4_Closed.glb')
