/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Necklace2_1: THREE.Mesh
    Necklace2_2: THREE.Mesh
    Necklace2_3: THREE.Mesh
  }
  materials: {
    DarkBrown: THREE.MeshStandardMaterial
    Red: THREE.MeshStandardMaterial
    Golden: THREE.MeshStandardMaterial
  }
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/glb/rpg_items_pack/Necklace2.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Necklace2_1.geometry} material={materials.DarkBrown} />
        <mesh geometry={nodes.Necklace2_2.geometry} material={materials.Red} />
        <mesh geometry={nodes.Necklace2_3.geometry} material={materials.Golden} />
      </group>
    </group>
  )
}

useGLTF.preload('/glb/rpg_items_pack/Necklace2.glb')
