/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Ring7_1: THREE.Mesh
    Ring7_2: THREE.Mesh
  }
  materials: {
    Teal: THREE.MeshStandardMaterial
    DarkTeal: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/glb/Ring7.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.Ring7_1.geometry} material={materials.Teal} />
        <mesh geometry={nodes.Ring7_2.geometry} material={materials.DarkTeal} />
      </group>
    </group>
  )
}

useGLTF.preload('/Ring7.glb')
