/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import type * as THREE from "three";
import type { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Book3_1: THREE.Mesh;
    Book3_2: THREE.Mesh;
    Book3_3: THREE.Mesh;
  };
  materials: {
    Cover: THREE.MeshStandardMaterial;
    Paper: THREE.MeshStandardMaterial;
    Ink: THREE.MeshStandardMaterial;
  };
};

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/glb/modular_dungeon_pack/Book3.glb",
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.11, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.Book3_1.geometry} material={materials.Cover} />
        <mesh geometry={nodes.Book3_2.geometry} material={materials.Paper} />
        <mesh geometry={nodes.Book3_3.geometry} material={materials.Ink} />
      </group>
    </group>
  );
}

useGLTF.preload("/glb/modular_dungeon_pack/Book3.glb");
