/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    ColumnBottom_1: THREE.Mesh
    ColumnBottom_2: THREE.Mesh
  }
  materials: {
    Rock: THREE.MeshStandardMaterial
    RockLight: THREE.MeshStandardMaterial
  }
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/glb/modular_dungeon_pack/ModularColumn_bottom.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.ColumnBottom_1.geometry} material={materials.Rock} />
        <mesh geometry={nodes.ColumnBottom_2.geometry} material={materials.RockLight} />
      </group>
    </group>
  )
}

useGLTF.preload('/glb/modular_dungeon_pack/ModularColumn_bottom.glb')
