/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Potion6_1: THREE.Mesh
    Potion6_2: THREE.Mesh
  }
  materials: {
    Yellow: THREE.MeshStandardMaterial
    Cork: THREE.MeshStandardMaterial
  }
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/glb/modular_dungeon_pack/Potion6.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Potion6_1.geometry} material={materials.Yellow} />
        <mesh geometry={nodes.Potion6_2.geometry} material={materials.Cork} />
      </group>
    </group>
  )
}

useGLTF.preload('/glb/modular_dungeon_pack/Potion6.glb')
