/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Potion_1: THREE.Mesh
    Potion_2: THREE.Mesh
    Potion_3: THREE.Mesh
  }
  materials: {
    Blue: THREE.MeshStandardMaterial
    Gold: THREE.MeshStandardMaterial
    Cork: THREE.MeshStandardMaterial
  }
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/glb/modular_dungeon_pack/Potion.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Potion_1.geometry} material={materials.Blue} />
        <mesh geometry={nodes.Potion_2.geometry} material={materials.Gold} />
        <mesh geometry={nodes.Potion_3.geometry} material={materials.Cork} />
      </group>
    </group>
  )
}

useGLTF.preload('/glb/modular_dungeon_pack/Potion.glb')
