/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    House1_1: THREE.Mesh
    House1_2: THREE.Mesh
    House1_3: THREE.Mesh
    House1_4: THREE.Mesh
  }
  materials: {
    Grey: THREE.MeshStandardMaterial
    DarkGrey: THREE.MeshStandardMaterial
    Brown: THREE.MeshStandardMaterial
    White: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/glb/House1.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100}>
        <mesh geometry={nodes.House1_1.geometry} material={materials.Grey} />
        <mesh geometry={nodes.House1_2.geometry} material={materials.DarkGrey} />
        <mesh geometry={nodes.House1_3.geometry} material={materials.Brown} />
        <mesh geometry={nodes.House1_4.geometry} material={materials.White} />
      </group>
    </group>
  )
}

useGLTF.preload('/House1.glb')
