/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import type * as THREE from "three";
import type { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Crate_Stack1_1: THREE.Mesh;
    Crate_Stack1_2: THREE.Mesh;
  };
  materials: {
    Wood_Light: THREE.MeshStandardMaterial;
    Wood: THREE.MeshStandardMaterial;
  };
};

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/glb/real_time_strategy_pack/Crate_Stack1.glb",
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.Crate_Stack1_1.geometry} material={materials.Wood_Light} />
        <mesh geometry={nodes.Crate_Stack1_2.geometry} material={materials.Wood} />
      </group>
    </group>
  );
}
