/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import type * as THREE from "three";
import type { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Mountain_Single_1: THREE.Mesh;
    Mountain_Single_2: THREE.Mesh;
  };
  materials: {
    Stone: THREE.MeshStandardMaterial;
    Dirt: THREE.MeshStandardMaterial;
  };
};

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/glb/real_time_strategy_pack/Mountain_Single.glb",
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.Mountain_Single_1.geometry} material={materials.Stone} />
        <mesh geometry={nodes.Mountain_Single_2.geometry} material={materials.Dirt} />
      </group>
    </group>
  );
}
