/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Beach_Body_1: THREE.SkinnedMesh
    Beach_Body_2: THREE.SkinnedMesh
    Beach_Feet_1: THREE.SkinnedMesh
    Beach_Feet_2: THREE.SkinnedMesh
    Beach_Head_1: THREE.SkinnedMesh
    Beach_Head_2: THREE.SkinnedMesh
    Beach_Head_3: THREE.SkinnedMesh
    Beach_Head_4: THREE.SkinnedMesh
    Beach_Head_5: THREE.SkinnedMesh
    Beach_Legs_1: THREE.SkinnedMesh
    Beach_Legs_2: THREE.SkinnedMesh
    Beach_Legs_3: THREE.SkinnedMesh
    Root: THREE.Bone
  }
  materials: {
    LightBrown: THREE.MeshStandardMaterial
    Skin: THREE.MeshStandardMaterial
    Red_Dark: THREE.MeshStandardMaterial
    Eyebrows: THREE.MeshStandardMaterial
    Eye: THREE.MeshStandardMaterial
    Hair: THREE.MeshStandardMaterial
    Earrings: THREE.MeshStandardMaterial
    White: THREE.MeshStandardMaterial
  }
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/glb/modular_men/Beach.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <primitive object={nodes.Root} />
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <skinnedMesh
          geometry={nodes.Beach_Body_1.geometry}
          material={materials.LightBrown}
          skeleton={nodes.Beach_Body_1.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Beach_Body_2.geometry}
          material={materials.Skin}
          skeleton={nodes.Beach_Body_2.skeleton}
        />
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <skinnedMesh
          geometry={nodes.Beach_Feet_1.geometry}
          material={materials.Skin}
          skeleton={nodes.Beach_Feet_1.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Beach_Feet_2.geometry}
          material={materials.Red_Dark}
          skeleton={nodes.Beach_Feet_2.skeleton}
        />
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <skinnedMesh
          geometry={nodes.Beach_Head_1.geometry}
          material={materials.Skin}
          skeleton={nodes.Beach_Head_1.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Beach_Head_2.geometry}
          material={materials.Eyebrows}
          skeleton={nodes.Beach_Head_2.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Beach_Head_3.geometry}
          material={materials.Eye}
          skeleton={nodes.Beach_Head_3.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Beach_Head_4.geometry}
          material={materials.Hair}
          skeleton={nodes.Beach_Head_4.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Beach_Head_5.geometry}
          material={materials.Earrings}
          skeleton={nodes.Beach_Head_5.skeleton}
        />
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <skinnedMesh
          geometry={nodes.Beach_Legs_1.geometry}
          material={materials.Skin}
          skeleton={nodes.Beach_Legs_1.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Beach_Legs_2.geometry}
          material={materials.Red_Dark}
          skeleton={nodes.Beach_Legs_2.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Beach_Legs_3.geometry}
          material={materials.White}
          skeleton={nodes.Beach_Legs_3.skeleton}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/glb/modular_men/Beach.glb')
