/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Body_AR_1_1: THREE.Mesh
    Body_AR_1_2: THREE.Mesh
    Body_AR_1_3: THREE.Mesh
  }
  materials: {
    Black: THREE.MeshStandardMaterial
    Main: THREE.MeshStandardMaterial
    White: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/Body_AR_1.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.Body_AR_1_1.geometry} material={materials.Black} />
        <mesh geometry={nodes.Body_AR_1_2.geometry} material={materials.Main} />
        <mesh geometry={nodes.Body_AR_1_3.geometry} material={materials.White} />
      </group>
    </group>
  )
}

useGLTF.preload('/Body_AR_1.glb')
