/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Magazine_Sniper: THREE.Mesh
    Sniper_1_1: THREE.Mesh
    Sniper_1_2: THREE.Mesh
    Sniper_1_3: THREE.Mesh
    Sniper_1_4: THREE.Mesh
  }
  materials: {
    Black: THREE.MeshStandardMaterial
    White: THREE.MeshStandardMaterial
    Grey: THREE.MeshStandardMaterial
    Main: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/glb/Sniper_1.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Magazine_Sniper.geometry}
        material={materials.Black}
        position={[0.21, 0.04, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.Sniper_1_1.geometry} material={materials.Black} />
        <mesh geometry={nodes.Sniper_1_2.geometry} material={materials.White} />
        <mesh geometry={nodes.Sniper_1_3.geometry} material={materials.Grey} />
        <mesh geometry={nodes.Sniper_1_4.geometry} material={materials.Main} />
      </group>
    </group>
  )
}

useGLTF.preload('/Sniper_1.glb')
