/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import type * as THREE from "three";
import type { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Magazine_Sniper_3: THREE.Mesh;
    Sniper_3_1: THREE.Mesh;
    Sniper_3_2: THREE.Mesh;
    Sniper_3_3: THREE.Mesh;
    Sniper_3_4: THREE.Mesh;
  };
  materials: {
    Black: THREE.MeshStandardMaterial;
    White: THREE.MeshStandardMaterial;
    Grey: THREE.MeshStandardMaterial;
    Main: THREE.MeshStandardMaterial;
  };
};

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/glb/modular_sci_fi_guns_pack/Sniper_3.glb",
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Magazine_Sniper_3.geometry}
        material={materials.Black}
        position={[0.2, 0.03, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.Sniper_3_1.geometry} material={materials.Black} />
        <mesh geometry={nodes.Sniper_3_2.geometry} material={materials.White} />
        <mesh geometry={nodes.Sniper_3_3.geometry} material={materials.Grey} />
        <mesh geometry={nodes.Sniper_3_4.geometry} material={materials.Main} />
      </group>
    </group>
  );
}

useGLTF.preload("/glb/modular_sci_fi_guns_pack/Sniper_3.glb");
