/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    SciFi_Body_1: THREE.SkinnedMesh
    SciFi_Body_2: THREE.SkinnedMesh
    SciFi_Body_3: THREE.SkinnedMesh
    SciFi_Body_4: THREE.SkinnedMesh
    SciFi_Body_5: THREE.SkinnedMesh
    SciFi_Feet_1: THREE.SkinnedMesh
    SciFi_Feet_2: THREE.SkinnedMesh
    SciFi_Head_1: THREE.SkinnedMesh
    SciFi_Head_2: THREE.SkinnedMesh
    SciFi_Head_3: THREE.SkinnedMesh
    SciFi_Head_4: THREE.SkinnedMesh
    SciFi_Head_5: THREE.SkinnedMesh
    SciFi_Legs_1: THREE.SkinnedMesh
    SciFi_Legs_2: THREE.SkinnedMesh
    SciFi_Legs_3: THREE.SkinnedMesh
    Root: THREE.Bone
  }
  materials: {
    Black: THREE.MeshStandardMaterial
    LightBlue: THREE.MeshStandardMaterial
    Skin: THREE.MeshStandardMaterial
    Metal: THREE.MeshStandardMaterial
    Blue: THREE.MeshStandardMaterial
    Hair_Black: THREE.MeshStandardMaterial
    Brown: THREE.MeshStandardMaterial
  }
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/glb/modular_women/SciFi.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <primitive object={nodes.Root} />
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <skinnedMesh
          geometry={nodes.SciFi_Body_1.geometry}
          material={materials.Black}
          skeleton={nodes.SciFi_Body_1.skeleton}
        />
        <skinnedMesh
          geometry={nodes.SciFi_Body_2.geometry}
          material={materials.LightBlue}
          skeleton={nodes.SciFi_Body_2.skeleton}
        />
        <skinnedMesh
          geometry={nodes.SciFi_Body_3.geometry}
          material={materials.Skin}
          skeleton={nodes.SciFi_Body_3.skeleton}
        />
        <skinnedMesh
          geometry={nodes.SciFi_Body_4.geometry}
          material={materials.Metal}
          skeleton={nodes.SciFi_Body_4.skeleton}
        />
        <skinnedMesh
          geometry={nodes.SciFi_Body_5.geometry}
          material={materials.Blue}
          skeleton={nodes.SciFi_Body_5.skeleton}
        />
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <skinnedMesh
          geometry={nodes.SciFi_Feet_1.geometry}
          material={materials.Black}
          skeleton={nodes.SciFi_Feet_1.skeleton}
        />
        <skinnedMesh
          geometry={nodes.SciFi_Feet_2.geometry}
          material={materials.Metal}
          skeleton={nodes.SciFi_Feet_2.skeleton}
        />
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <skinnedMesh
          geometry={nodes.SciFi_Head_1.geometry}
          material={materials.Black}
          skeleton={nodes.SciFi_Head_1.skeleton}
        />
        <skinnedMesh
          geometry={nodes.SciFi_Head_2.geometry}
          material={materials.Skin}
          skeleton={nodes.SciFi_Head_2.skeleton}
        />
        <skinnedMesh
          geometry={nodes.SciFi_Head_3.geometry}
          material={materials.Blue}
          skeleton={nodes.SciFi_Head_3.skeleton}
        />
        <skinnedMesh
          geometry={nodes.SciFi_Head_4.geometry}
          material={materials.Hair_Black}
          skeleton={nodes.SciFi_Head_4.skeleton}
        />
        <skinnedMesh
          geometry={nodes.SciFi_Head_5.geometry}
          material={materials.Brown}
          skeleton={nodes.SciFi_Head_5.skeleton}
        />
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <skinnedMesh
          geometry={nodes.SciFi_Legs_1.geometry}
          material={materials.Black}
          skeleton={nodes.SciFi_Legs_1.skeleton}
        />
        <skinnedMesh
          geometry={nodes.SciFi_Legs_2.geometry}
          material={materials.LightBlue}
          skeleton={nodes.SciFi_Legs_2.skeleton}
        />
        <skinnedMesh
          geometry={nodes.SciFi_Legs_3.geometry}
          material={materials.Metal}
          skeleton={nodes.SciFi_Legs_3.skeleton}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/glb/modular_women/SciFi.glb')
