/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Soldier_Body_1: THREE.SkinnedMesh
    Soldier_Body_2: THREE.SkinnedMesh
    Soldier_Body_3: THREE.SkinnedMesh
    Soldier_Feet_1: THREE.SkinnedMesh
    Soldier_Feet_2: THREE.SkinnedMesh
    Soldier_Head_1: THREE.SkinnedMesh
    Soldier_Head_2: THREE.SkinnedMesh
    Soldier_Head_3: THREE.SkinnedMesh
    Soldier_Legs_1: THREE.SkinnedMesh
    Soldier_Legs_2: THREE.SkinnedMesh
    Soldier_Legs_3: THREE.SkinnedMesh
    Root: THREE.Bone
  }
  materials: {
    Black: THREE.MeshStandardMaterial
    Swat: THREE.MeshStandardMaterial
    Skin: THREE.MeshStandardMaterial
    Grey: THREE.MeshStandardMaterial
    Hair_Brown: THREE.MeshStandardMaterial
    Brown: THREE.MeshStandardMaterial
  }
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/glb/modular_women/Soldier.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <primitive object={nodes.Root} />
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <skinnedMesh
          geometry={nodes.Soldier_Body_1.geometry}
          material={materials.Black}
          skeleton={nodes.Soldier_Body_1.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Soldier_Body_2.geometry}
          material={materials.Swat}
          skeleton={nodes.Soldier_Body_2.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Soldier_Body_3.geometry}
          material={materials.Skin}
          skeleton={nodes.Soldier_Body_3.skeleton}
        />
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <skinnedMesh
          geometry={nodes.Soldier_Feet_1.geometry}
          material={materials.Black}
          skeleton={nodes.Soldier_Feet_1.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Soldier_Feet_2.geometry}
          material={materials.Grey}
          skeleton={nodes.Soldier_Feet_2.skeleton}
        />
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <skinnedMesh
          geometry={nodes.Soldier_Head_1.geometry}
          material={materials.Skin}
          skeleton={nodes.Soldier_Head_1.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Soldier_Head_2.geometry}
          material={materials.Hair_Brown}
          skeleton={nodes.Soldier_Head_2.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Soldier_Head_3.geometry}
          material={materials.Brown}
          skeleton={nodes.Soldier_Head_3.skeleton}
        />
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <skinnedMesh
          geometry={nodes.Soldier_Legs_1.geometry}
          material={materials.Black}
          skeleton={nodes.Soldier_Legs_1.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Soldier_Legs_2.geometry}
          material={materials.Swat}
          skeleton={nodes.Soldier_Legs_2.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Soldier_Legs_3.geometry}
          material={materials.Grey}
          skeleton={nodes.Soldier_Legs_3.skeleton}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/glb/modular_women/Soldier.glb')
