/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Bush_Small: THREE.Mesh
  }
  materials: {
    Bush_Leaves: THREE.MeshStandardMaterial
  }
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/glb/stylized_nature_pack/Bush_Small.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Bush_Small.geometry} material={materials.Bush_Leaves} rotation={[1.12, -0.22, 2.63]} />
    </group>
  )
}

useGLTF.preload('/glb/stylized_nature_pack/Bush_Small.glb')
