/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Bush_Flowers_1: THREE.Mesh
    Bush_Flowers_2: THREE.Mesh
  }
  materials: {
    Bush_Leaves: THREE.MeshStandardMaterial
    Flowers: THREE.MeshStandardMaterial
  }
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/glb/stylized_nature_pack/Bush_Flowers.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[0.87, 0.72, -0.67]} scale={100}>
        <mesh geometry={nodes.Bush_Flowers_1.geometry} material={materials.Bush_Leaves} />
        <mesh geometry={nodes.Bush_Flowers_2.geometry} material={materials.Flowers} />
      </group>
    </group>
  )
}

useGLTF.preload('/glb/stylized_nature_pack/Bush_Flowers.glb')
