/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    DeadTree_5: THREE.Mesh
  }
  materials: {
    NormalTree_Bark: THREE.MeshStandardMaterial
  }
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/glb/stylized_nature_pack/DeadTree_5.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.DeadTree_5.geometry} material={materials.NormalTree_Bark} />
    </group>
  )
}

useGLTF.preload('/glb/stylized_nature_pack/DeadTree_5.glb')
