/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cylinder009: THREE.Mesh
    Cylinder009_1: THREE.Mesh
  }
  materials: {
    NormalTree_Bark: THREE.MeshStandardMaterial
    NormalTree_Leaves: THREE.MeshStandardMaterial
  }
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/glb/stylized_nature_pack/NormalTree_3.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cylinder009.geometry} material={materials.NormalTree_Bark} />
      <mesh geometry={nodes.Cylinder009_1.geometry} material={materials.NormalTree_Leaves} />
    </group>
  )
}

useGLTF.preload('/glb/stylized_nature_pack/NormalTree_3.glb')
