/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cube007: THREE.Mesh
    Cube007_1: THREE.Mesh
  }
  materials: {
    PalmTree_Trunk: THREE.MeshStandardMaterial
    PalmTree_Leaves: THREE.MeshStandardMaterial
  }
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/glb/stylized_nature_pack/PalmTree_2.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube007.geometry} material={materials.PalmTree_Trunk} />
      <mesh geometry={nodes.Cube007_1.geometry} material={materials.PalmTree_Leaves} />
    </group>
  )
}

useGLTF.preload('/glb/stylized_nature_pack/PalmTree_2.glb')
