/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Table_Small_1: THREE.Mesh
    Table_Small_2: THREE.Mesh
    Table_Small_3: THREE.Mesh
  }
  materials: {
    Wood: THREE.MeshStandardMaterial
    DarkWood: THREE.MeshStandardMaterial
    DarkMetal: THREE.MeshStandardMaterial
  }
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/glb/modular_dungeon_1/Table_Small.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Table_Small_1.geometry} material={materials.Wood} />
        <mesh geometry={nodes.Table_Small_2.geometry} material={materials.DarkWood} />
        <mesh geometry={nodes.Table_Small_3.geometry} material={materials.DarkMetal} />
      </group>
    </group>
  )
}

useGLTF.preload('/glb/modular_dungeon_1/Table_Small.glb')
