/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Door_1: THREE.Mesh
    Door_2: THREE.Mesh
    LeftDoor_1: THREE.Mesh
    LeftDoor_2: THREE.Mesh
    RightDoor_1: THREE.Mesh
    RightDoor_2: THREE.Mesh
  }
  materials: {
    DarkWood: THREE.MeshStandardMaterial
    LightWood: THREE.MeshStandardMaterial
    DarkWood: THREE.MeshStandardMaterial
    LightWood: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/glb/Door.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.Door_1.geometry} material={materials.DarkWood} />
        <mesh geometry={nodes.Door_2.geometry} material={materials.LightWood} />
      </group>
      <group position={[-0.36, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.LeftDoor_1.geometry} material={materials.DarkWood} />
        <mesh geometry={nodes.LeftDoor_2.geometry} material={materials.LightWood} />
      </group>
      <group position={[0.37, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.RightDoor_1.geometry} material={materials.DarkWood} />
        <mesh geometry={nodes.RightDoor_2.geometry} material={materials.LightWood} />
      </group>
    </group>
  )
}

useGLTF.preload('/Door.glb')
