/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    LargeTower: THREE.Mesh
  }
  materials: {
    ['LightRock.001']: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/LargeTower.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.LargeTower.geometry} material={materials['LightRock.001']} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
    </group>
  )
}

useGLTF.preload('/LargeTower.glb')
