/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Sword_1: THREE.Mesh
    Sword_2: THREE.Mesh
    Sword_3: THREE.Mesh
    Sword_4: THREE.Mesh
  }
  materials: {
    Red: THREE.MeshStandardMaterial
    Gold: THREE.MeshStandardMaterial
    Metal: THREE.MeshStandardMaterial
    Brown: THREE.MeshStandardMaterial
  }
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/glb/single_knight_pack/Sword.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Sword_1.geometry} material={materials.Red} />
        <mesh geometry={nodes.Sword_2.geometry} material={materials.Gold} />
        <mesh geometry={nodes.Sword_3.geometry} material={materials.Metal} />
        <mesh geometry={nodes.Sword_4.geometry} material={materials.Brown} />
      </group>
    </group>
  )
}

useGLTF.preload('/glb/single_knight_pack/Sword.glb')
