/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Bag_Coins_1: THREE.Mesh
    Bag_Coins_2: THREE.Mesh
  }
  materials: {
    Bag: THREE.MeshStandardMaterial
    Gold: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/glb/modular_dungeon_1/Bag_Coins.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.Bag_Coins_1.geometry} material={materials.Bag} />
        <mesh geometry={nodes.Bag_Coins_2.geometry} material={materials.Gold} />
      </group>
    </group>
  )
}

useGLTF.preload('/glb/modular_dungeon_1/Bag_Coins.glb')
