/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Decorative_Wall_1: THREE.Mesh
    Decorative_Wall_2: THREE.Mesh
  }
  materials: {
    Wall_Dark: THREE.MeshStandardMaterial
    Wall_Highlights: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/Decorative_Wall.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.Decorative_Wall_1.geometry} material={materials.Wall_Dark} />
        <mesh geometry={nodes.Decorative_Wall_2.geometry} material={materials.Wall_Highlights} />
      </group>
    </group>
  )
}

useGLTF.preload('/Decorative_Wall.glb')
