/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GenericAnimationController } from '@/components/canvas/GenericAnimationController'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Stag_Horns: THREE.Mesh
    Stag_1: THREE.SkinnedMesh
    Stag_2: THREE.SkinnedMesh
    Stag_3: THREE.SkinnedMesh
    Stag_4: THREE.SkinnedMesh
    Stag_5: THREE.SkinnedMesh
    Body: THREE.Bone
    IKBackLegL: THREE.Bone
    IKFrontLegL: THREE.Bone
    IKBackLegR: THREE.Bone
    IKFrontLegR: THREE.Bone
  }
  materials: {
    ['Material.001']: THREE.MeshStandardMaterial
    ['Material.003']: THREE.MeshStandardMaterial
    Material: THREE.MeshStandardMaterial
    ['Material.010']: THREE.MeshStandardMaterial
    ['Material.001']: THREE.MeshStandardMaterial
    ['Material.011']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

type ActionName =
  | 'AnimalArmature|Attack_Headbutt'
  | 'AnimalArmature|Attack_Kick'
  | 'AnimalArmature|Death'
  | 'AnimalArmature|Eating'
  | 'AnimalArmature|Gallop'
  | 'AnimalArmature|Gallop_Jump'
  | 'AnimalArmature|Idle'
  | 'AnimalArmature|Idle_2'
  | 'AnimalArmature|Idle_Headlow'
  | 'AnimalArmature|Idle_HitReact_Left'
  | 'AnimalArmature|Idle_HitReact_Right'
  | 'AnimalArmature|Jump_toIdle'
  | 'AnimalArmature|Walk'
interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials, animations } = useGLTF('/glb/animals_pack/Stag.glb') as unknown as GLTFResult
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <GenericAnimationController actions={actions} />
      <group name='Root_Scene'>
        <group name='RootNode'>
          <group name='AnimalArmature' rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <primitive object={nodes.Body} />
            <primitive object={nodes.IKBackLegL} />
            <primitive object={nodes.IKFrontLegL} />
            <primitive object={nodes.IKBackLegR} />
            <primitive object={nodes.IKFrontLegR} />
          </group>
          <group name='Stag' rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <skinnedMesh
              name='Stag_1'
              geometry={nodes.Stag_1.geometry}
              material={materials['Material.003']}
              skeleton={nodes.Stag_1.skeleton}
            />
            <skinnedMesh
              name='Stag_2'
              geometry={nodes.Stag_2.geometry}
              material={materials.Material}
              skeleton={nodes.Stag_2.skeleton}
            />
            <skinnedMesh
              name='Stag_3'
              geometry={nodes.Stag_3.geometry}
              material={materials['Material.010']}
              skeleton={nodes.Stag_3.skeleton}
            />
            <skinnedMesh
              name='Stag_4'
              geometry={nodes.Stag_4.geometry}
              material={materials['Material.001']}
              skeleton={nodes.Stag_4.skeleton}
            />
            <skinnedMesh
              name='Stag_5'
              geometry={nodes.Stag_5.geometry}
              material={materials['Material.011']}
              skeleton={nodes.Stag_5.skeleton}
            />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/glb/animals_pack/Stag.glb')
