export { Model as Dolphin } from "./Dolphin"
export { Model as Fish1 } from "./Fish1"
export { Model as Fish2 } from "./Fish2"
export { Model as Fish3 } from "./Fish3"
export { Model as Ray } from "./Ray"
export { Model as Shark } from "./Shark"
export { Model as Whale } from "./Whale"