/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Punk_Body_1: THREE.SkinnedMesh
    Punk_Body_2: THREE.SkinnedMesh
    Punk_Body_3: THREE.SkinnedMesh
    Punk_Feet_1: THREE.SkinnedMesh
    Punk_Feet_2: THREE.SkinnedMesh
    Punk_Head_1: THREE.SkinnedMesh
    Punk_Head_2: THREE.SkinnedMesh
    Punk_Head_3: THREE.SkinnedMesh
    Punk_Head_4: THREE.SkinnedMesh
    Punk_Head_5: THREE.SkinnedMesh
    Punk_Head_6: THREE.SkinnedMesh
    Punk_Legs_1: THREE.SkinnedMesh
    Punk_Legs_2: THREE.SkinnedMesh
    Root: THREE.Bone
  }
  materials: {
    Black: THREE.MeshStandardMaterial
    White: THREE.MeshStandardMaterial
    Skin: THREE.MeshStandardMaterial
    Red_Dark: THREE.MeshStandardMaterial
    Earrings: THREE.MeshStandardMaterial
    Red: THREE.MeshStandardMaterial
    Eyebrows: THREE.MeshStandardMaterial
    Eye: THREE.MeshStandardMaterial
    LightBlue: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/glb/modular_men/Punk.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <primitive object={nodes.Root} />
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <skinnedMesh
          geometry={nodes.Punk_Body_1.geometry}
          material={materials.Black}
          skeleton={nodes.Punk_Body_1.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Punk_Body_2.geometry}
          material={materials.White}
          skeleton={nodes.Punk_Body_2.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Punk_Body_3.geometry}
          material={materials.Skin}
          skeleton={nodes.Punk_Body_3.skeleton}
        />
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <skinnedMesh
          geometry={nodes.Punk_Feet_1.geometry}
          material={materials.Black}
          skeleton={nodes.Punk_Feet_1.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Punk_Feet_2.geometry}
          material={materials.Skin}
          skeleton={nodes.Punk_Feet_2.skeleton}
        />
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <skinnedMesh
          geometry={nodes.Punk_Head_1.geometry}
          material={materials.Skin}
          skeleton={nodes.Punk_Head_1.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Punk_Head_2.geometry}
          material={materials.Red_Dark}
          skeleton={nodes.Punk_Head_2.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Punk_Head_3.geometry}
          material={materials.Earrings}
          skeleton={nodes.Punk_Head_3.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Punk_Head_4.geometry}
          material={materials.Red}
          skeleton={nodes.Punk_Head_4.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Punk_Head_5.geometry}
          material={materials.Eyebrows}
          skeleton={nodes.Punk_Head_5.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Punk_Head_6.geometry}
          material={materials.Eye}
          skeleton={nodes.Punk_Head_6.skeleton}
        />
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <skinnedMesh
          geometry={nodes.Punk_Legs_1.geometry}
          material={materials.Skin}
          skeleton={nodes.Punk_Legs_1.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Punk_Legs_2.geometry}
          material={materials.LightBlue}
          skeleton={nodes.Punk_Legs_2.skeleton}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/glb/modular_men/Punk.glb')
