/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    House_4_1: THREE.Mesh
    House_4_2: THREE.Mesh
    House_4_3: THREE.Mesh
    House_4_4: THREE.Mesh
    House_4_5: THREE.Mesh
  }
  materials: {
    Stone_Light: THREE.MeshStandardMaterial
    Stone_Dark: THREE.MeshStandardMaterial
    Stone: THREE.MeshStandardMaterial
    Wood: THREE.MeshStandardMaterial
    Wood_Side: THREE.MeshStandardMaterial
  }
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/glb/medieval_village_pack/House_4.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.House_4_1.geometry} material={materials.Stone_Light} />
        <mesh geometry={nodes.House_4_2.geometry} material={materials.Stone_Dark} />
        <mesh geometry={nodes.House_4_3.geometry} material={materials.Stone} />
        <mesh geometry={nodes.House_4_4.geometry} material={materials.Wood} />
        <mesh geometry={nodes.House_4_5.geometry} material={materials.Wood_Side} />
      </group>
    </group>
  )
}

useGLTF.preload('/glb/medieval_village_pack/House_4.glb')
