/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import type * as THREE from "three";
import type { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Package_1_1: THREE.Mesh;
    Package_1_2: THREE.Mesh;
  };
  materials: {
    Bag: THREE.MeshStandardMaterial;
    Leather: THREE.MeshStandardMaterial;
  };
};

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/glb/medieval_village_pack/Package_1.glb",
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.Package_1_1.geometry} material={materials.Bag} />
        <mesh geometry={nodes.Package_1_2.geometry} material={materials.Leather} />
      </group>
    </group>
  );
}

useGLTF.preload("/glb/medieval_village_pack/Package_1.glb");
