/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Sawmill_1: THREE.Mesh
    Sawmill_2: THREE.Mesh
    Sawmill_3: THREE.Mesh
    Sawmill_4: THREE.Mesh
    Sawmill_5: THREE.Mesh
    Sawmill_6: THREE.Mesh
    Sawmill_7: THREE.Mesh
    Sawmill_8: THREE.Mesh
    Sawmill_9: THREE.Mesh
    Sawmill_10: THREE.Mesh
  }
  materials: {
    RoofTiles_Red: THREE.MeshStandardMaterial
    Wood: THREE.MeshStandardMaterial
    Wood_Side: THREE.MeshStandardMaterial
    DarkWood: THREE.MeshStandardMaterial
    Metal: THREE.MeshStandardMaterial
    Windows: THREE.MeshStandardMaterial
    Wood_Light: THREE.MeshStandardMaterial
    Stone_Dark: THREE.MeshStandardMaterial
    Plaster: THREE.MeshStandardMaterial
    Stone_Light: THREE.MeshStandardMaterial
  }
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/glb/medieval_village_pack/Sawmill.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Sawmill_1.geometry} material={materials.RoofTiles_Red} />
        <mesh geometry={nodes.Sawmill_2.geometry} material={materials.Wood} />
        <mesh geometry={nodes.Sawmill_3.geometry} material={materials.Wood_Side} />
        <mesh geometry={nodes.Sawmill_4.geometry} material={materials.DarkWood} />
        <mesh geometry={nodes.Sawmill_5.geometry} material={materials.Metal} />
        <mesh geometry={nodes.Sawmill_6.geometry} material={materials.Windows} />
        <mesh geometry={nodes.Sawmill_7.geometry} material={materials.Wood_Light} />
        <mesh geometry={nodes.Sawmill_8.geometry} material={materials.Stone_Dark} />
        <mesh geometry={nodes.Sawmill_9.geometry} material={materials.Plaster} />
        <mesh geometry={nodes.Sawmill_10.geometry} material={materials.Stone_Light} />
      </group>
    </group>
  )
}

useGLTF.preload('/glb/medieval_village_pack/Sawmill.glb')
