/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Stable_1: THREE.Mesh
    Stable_2: THREE.Mesh
    Stable_3: THREE.Mesh
    Stable_4: THREE.Mesh
    Stable_5: THREE.Mesh
    Stable_6: THREE.Mesh
    Stable_7: THREE.Mesh
    Stable_8: THREE.Mesh
  }
  materials: {
    Wood: THREE.MeshStandardMaterial
    Wood_Side: THREE.MeshStandardMaterial
    RoofTiles: THREE.MeshStandardMaterial
    Beige: THREE.MeshStandardMaterial
    Wood_Light: THREE.MeshStandardMaterial
    Windows: THREE.MeshStandardMaterial
    Stone_Light: THREE.MeshStandardMaterial
    Stone_Dark: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/glb/Stable.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.Stable_1.geometry} material={materials.Wood} />
        <mesh geometry={nodes.Stable_2.geometry} material={materials.Wood_Side} />
        <mesh geometry={nodes.Stable_3.geometry} material={materials.RoofTiles} />
        <mesh geometry={nodes.Stable_4.geometry} material={materials.Beige} />
        <mesh geometry={nodes.Stable_5.geometry} material={materials.Wood_Light} />
        <mesh geometry={nodes.Stable_6.geometry} material={materials.Windows} />
        <mesh geometry={nodes.Stable_7.geometry} material={materials.Stone_Light} />
        <mesh geometry={nodes.Stable_8.geometry} material={materials.Stone_Dark} />
      </group>
    </group>
  )
}

useGLTF.preload('/Stable.glb')
