/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import type * as THREE from "three";
import type { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Stop_1: THREE.Mesh;
    Stop_2: THREE.Mesh;
    Stop_3: THREE.Mesh;
  };
  materials: {
    White: THREE.MeshStandardMaterial;
    Pole: THREE.MeshStandardMaterial;
    Red: THREE.MeshStandardMaterial;
  };
};

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/glb/street_pack/Sign_Stop.glb") as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.Stop_1.geometry} material={materials.White} />
        <mesh geometry={nodes.Stop_2.geometry} material={materials.Pole} />
        <mesh geometry={nodes.Stop_3.geometry} material={materials.Red} />
      </group>
    </group>
  );
}

useGLTF.preload("/glb/street_pack/Sign_Stop.glb");
