/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Streetlight_Double_1: THREE.Mesh
    Streetlight_Double_2: THREE.Mesh
    Streetlight_Double_3: THREE.Mesh
  }
  materials: {
    ['Green.002']: THREE.MeshStandardMaterial
    ['Glass.002']: THREE.MeshStandardMaterial
    ['Light.002']: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/glb/Streetlight_Double.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.Streetlight_Double_1.geometry} material={materials['Green.002']} />
        <mesh geometry={nodes.Streetlight_Double_2.geometry} material={materials['Glass.002']} />
        <mesh geometry={nodes.Streetlight_Double_3.geometry} material={materials['Light.002']} />
      </group>
    </group>
  )
}

useGLTF.preload('/Streetlight_Double.glb')
