/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import type * as THREE from "three";
import type { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Spitfire: THREE.Mesh;
  };
  materials: {
    Texture: THREE.MeshStandardMaterial;
  };
};

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/glb/spaceships_pack/Spitfire.glb",
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Spitfire.geometry} material={materials.Texture} />
    </group>
  );
}

useGLTF.preload("/glb/spaceships_pack/Spitfire.glb");
