/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useLayoutEffect, useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useAnimationsWithCleanup } from '@/hooks/useAnimationsWithCleanup'
import { GenericAnimationController } from '@/components/canvas/GenericAnimationController'
import { GLTF } from 'three-stdlib'
import { DoubleSide } from 'three'

type GLTFResult = GLTF & {
  nodes: {
    BlueTang_1: THREE.SkinnedMesh
    BlueTang_2: THREE.SkinnedMesh
    BlueTang_3: THREE.SkinnedMesh
    BlueTang_4: THREE.SkinnedMesh
    Main1: THREE.Bone
  }
  materials: {
    BlueTang_Dark: THREE.MeshStandardMaterial
    BlueTang_Fins: THREE.MeshStandardMaterial
    Eyes: THREE.MeshStandardMaterial
    BlueTang_Main: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

type ActionName =
  | 'Fish_Armature|Attack'
  | 'Fish_Armature|Death'
  | 'Fish_Armature|Out_Of_Water'
  | 'Fish_Armature|Swimming_Fast'
  | 'Fish_Armature|Swimming_Impulse'
  | 'Fish_Armature|Swimming_Normal'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials, animations } = useGLTF('/glb/cute_fish_pack/BlueTang.glb') as unknown as GLTFResult
  const { actions } = useAnimationsWithCleanup(animations, group)

  useLayoutEffect(() => {
    Object.keys(materials).forEach((key) => {
      Object.assign(materials[key], { side: DoubleSide })
    })
  })
  return (
    <group ref={group} {...props} dispose={null}>
      <GenericAnimationController actions={actions} />
      <group name='Root_Scene'>
        <group name='RootNode'>
          <group name='Fish_Armature' rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <primitive object={nodes.Main1} />
          </group>
          <group name='BlueTang' rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <skinnedMesh
              name='BlueTang_1'
              geometry={nodes.BlueTang_1.geometry}
              material={materials.BlueTang_Dark}
              skeleton={nodes.BlueTang_1.skeleton}
            />
            <skinnedMesh
              name='BlueTang_2'
              geometry={nodes.BlueTang_2.geometry}
              material={materials.BlueTang_Fins}
              skeleton={nodes.BlueTang_2.skeleton}
            />
            <skinnedMesh
              name='BlueTang_3'
              geometry={nodes.BlueTang_3.geometry}
              material={materials.Eyes}
              skeleton={nodes.BlueTang_3.skeleton}
            />
            <skinnedMesh
              name='BlueTang_4'
              geometry={nodes.BlueTang_4.geometry}
              material={materials.BlueTang_Main}
              skeleton={nodes.BlueTang_4.skeleton}
            />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/glb/cute_fish_pack/BlueTang.glb')
