/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    CardinalFish_1: THREE.SkinnedMesh
    CardinalFish_2: THREE.SkinnedMesh
    CardinalFish_3: THREE.SkinnedMesh
    CardinalFish_4: THREE.SkinnedMesh
    Main1: THREE.Bone
  }
  materials: {
    CardinalFish_Fins: THREE.MeshStandardMaterial
    Eyes: THREE.MeshStandardMaterial
    CardinalFish_Main: THREE.MeshStandardMaterial
    CardinalFish_Light: THREE.MeshStandardMaterial
  }
}

type ActionName = 'Fish_Armature|Attack' | 'Fish_Armature|Death' | 'Fish_Armature|Out_Of_Water' | 'Fish_Armature|Swimming_Fast' | 'Fish_Armature|Swimming_Impulse' | 'Fish_Armature|Swimming_Normal'
type GLTFActions = Record<ActionName, THREE.AnimationAction>

export function Model(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials, animations } = useGLTF('/CardinalFish.glb') as GLTFResult
  const { actions } = useAnimations<GLTFActions>(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Root_Scene">
        <group name="RootNode">
          <group name="Fish_Armature" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <primitive object={nodes.Main1} />
          </group>
          <group name="CardinalFish" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <skinnedMesh name="CardinalFish_1" geometry={nodes.CardinalFish_1.geometry} material={materials.CardinalFish_Fins} skeleton={nodes.CardinalFish_1.skeleton} />
            <skinnedMesh name="CardinalFish_2" geometry={nodes.CardinalFish_2.geometry} material={materials.Eyes} skeleton={nodes.CardinalFish_2.skeleton} />
            <skinnedMesh name="CardinalFish_3" geometry={nodes.CardinalFish_3.geometry} material={materials.CardinalFish_Main} skeleton={nodes.CardinalFish_3.skeleton} />
            <skinnedMesh name="CardinalFish_4" geometry={nodes.CardinalFish_4.geometry} material={materials.CardinalFish_Light} skeleton={nodes.CardinalFish_4.skeleton} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/CardinalFish.glb')
