/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    FishingRod_Lvl3_1: THREE.Mesh
    FishingRod_Lvl3_2: THREE.Mesh
  }
  materials: {
    Metal: THREE.MeshStandardMaterial
    Black: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/FishingRod_Lvl3.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.FishingRod_Lvl3_1.geometry} material={materials.Metal} />
        <mesh geometry={nodes.FishingRod_Lvl3_2.geometry} material={materials.Black} />
      </group>
    </group>
  )
}

useGLTF.preload('/FishingRod_Lvl3.glb')
