/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Flatfish_1: THREE.SkinnedMesh
    Flatfish_2: THREE.SkinnedMesh
    Flatfish_3: THREE.SkinnedMesh
    Flatfish_4: THREE.SkinnedMesh
    Flatfish_5: THREE.SkinnedMesh
    Main1: THREE.Bone
  }
  materials: {
    Flatfish_Light: THREE.MeshStandardMaterial
    Flatfish_Teeth: THREE.MeshStandardMaterial
    Eyes: THREE.MeshStandardMaterial
    Flatfish_Main: THREE.MeshStandardMaterial
    Flatfish_Fins: THREE.MeshStandardMaterial
  },
  animations: GLTFAction[],
}

type ActionName = 'Fish_Armature|Attack' | 'Fish_Armature|Death' | 'Fish_Armature|Out_Of_Water' | 'Fish_Armature|Swimming_Fast' | 'Fish_Armature|Swimming_Impulse' | 'Fish_Armature|Swimming_Normal'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials, animations } = useGLTF('/glb/cute_fish_pack/Flatfish.glb') as unknown as GLTFResult
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Root_Scene">
        <group name="RootNode">
          <group name="Fish_Armature" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <primitive object={nodes.Main1} />
          </group>
          <group name="Flatfish" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <skinnedMesh name="Flatfish_1" geometry={nodes.Flatfish_1.geometry} material={materials.Flatfish_Light} skeleton={nodes.Flatfish_1.skeleton} />
            <skinnedMesh name="Flatfish_2" geometry={nodes.Flatfish_2.geometry} material={materials.Flatfish_Teeth} skeleton={nodes.Flatfish_2.skeleton} />
            <skinnedMesh name="Flatfish_3" geometry={nodes.Flatfish_3.geometry} material={materials.Eyes} skeleton={nodes.Flatfish_3.skeleton} />
            <skinnedMesh name="Flatfish_4" geometry={nodes.Flatfish_4.geometry} material={materials.Flatfish_Main} skeleton={nodes.Flatfish_4.skeleton} />
            <skinnedMesh name="Flatfish_5" geometry={nodes.Flatfish_5.geometry} material={materials.Flatfish_Fins} skeleton={nodes.Flatfish_5.skeleton} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/glb/cute_fish_pack/Flatfish.glb')
