/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Lure_5_1: THREE.Mesh
    Lure_5_2: THREE.Mesh
    Lure_5_3: THREE.Mesh
    Lure_5_4: THREE.Mesh
  }
  materials: {
    Lure_Blue: THREE.MeshStandardMaterial
    Lure_Yellow: THREE.MeshStandardMaterial
    Metal: THREE.MeshStandardMaterial
    Black: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/Lure_5.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.Lure_5_1.geometry} material={materials.Lure_Blue} />
        <mesh geometry={nodes.Lure_5_2.geometry} material={materials.Lure_Yellow} />
        <mesh geometry={nodes.Lure_5_3.geometry} material={materials.Metal} />
        <mesh geometry={nodes.Lure_5_4.geometry} material={materials.Black} />
      </group>
    </group>
  )
}

useGLTF.preload('/Lure_5.glb')
