/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useLayoutEffect, useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { DoubleSide } from 'three'

type GLTFResult = GLTF & {
  nodes: {
    Lure_6_1: THREE.Mesh
    Lure_6_2: THREE.Mesh
    Lure_6_3: THREE.Mesh
    Lure_6_4: THREE.Mesh
    Lure_6_5: THREE.Mesh
    Lure_6_6: THREE.Mesh
  }
  materials: {
    Lure_Pink: THREE.MeshStandardMaterial
    Lure_Blue: THREE.MeshStandardMaterial
    Lure_Yellow: THREE.MeshStandardMaterial
    Lure_Red: THREE.MeshStandardMaterial
    Metal: THREE.MeshStandardMaterial
    Black: THREE.MeshStandardMaterial
  }
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/glb/cute_fish_pack/Lure_6.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.Lure_6_1.geometry} material={materials.Lure_Pink} />
        <mesh geometry={nodes.Lure_6_2.geometry} material={materials.Lure_Blue} />
        <mesh geometry={nodes.Lure_6_3.geometry} material={materials.Lure_Yellow} />
        <mesh geometry={nodes.Lure_6_4.geometry} material={materials.Lure_Red} />
        <mesh geometry={nodes.Lure_6_5.geometry} material={materials.Metal} />
        <mesh geometry={nodes.Lure_6_6.geometry} material={materials.Black} />
      </group>
    </group>
  )
}

useGLTF.preload('/glb/cute_fish_pack/Lure_6.glb')
