/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Lure_2_1: THREE.Mesh
    Lure_2_2: THREE.Mesh
    Lure_2_3: THREE.Mesh
    Lure_2_4: THREE.Mesh
  }
  materials: {
    Lure_Red: THREE.MeshStandardMaterial
    Lure_Grey: THREE.MeshStandardMaterial
    Metal: THREE.MeshStandardMaterial
    Black: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/Lure_2.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0, 0.78]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.Lure_2_1.geometry} material={materials.Lure_Red} />
        <mesh geometry={nodes.Lure_2_2.geometry} material={materials.Lure_Grey} />
        <mesh geometry={nodes.Lure_2_3.geometry} material={materials.Metal} />
        <mesh geometry={nodes.Lure_2_4.geometry} material={materials.Black} />
      </group>
    </group>
  )
}

useGLTF.preload('/Lure_2.glb')
