/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    ParrotFish_1: THREE.SkinnedMesh
    ParrotFish_2: THREE.SkinnedMesh
    ParrotFish_3: THREE.SkinnedMesh
    ParrotFish_4: THREE.SkinnedMesh
    ParrotFish_5: THREE.SkinnedMesh
    Main1: THREE.Bone
  }
  materials: {
    ParrotFish_Fins: THREE.MeshStandardMaterial
    ParrotFish_Light: THREE.MeshStandardMaterial
    ParrotFish_Main: THREE.MeshStandardMaterial
    ParrotFish_Teeth: THREE.MeshStandardMaterial
    Eyes: THREE.MeshStandardMaterial
  }
}

type ActionName = 'Fish_Armature|Attack' | 'Fish_Armature|Death' | 'Fish_Armature|Out_Of_Water' | 'Fish_Armature|Swimming_Fast' | 'Fish_Armature|Swimming_Impulse' | 'Fish_Armature|Swimming_Normal'
type GLTFActions = Record<ActionName, THREE.AnimationAction>

export function Model(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials, animations } = useGLTF('/ParrotFish.glb') as GLTFResult
  const { actions } = useAnimations<GLTFActions>(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Root_Scene">
        <group name="RootNode">
          <group name="Fish_Armature" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <primitive object={nodes.Main1} />
          </group>
          <group name="ParrotFish" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <skinnedMesh name="ParrotFish_1" geometry={nodes.ParrotFish_1.geometry} material={materials.ParrotFish_Fins} skeleton={nodes.ParrotFish_1.skeleton} />
            <skinnedMesh name="ParrotFish_2" geometry={nodes.ParrotFish_2.geometry} material={materials.ParrotFish_Light} skeleton={nodes.ParrotFish_2.skeleton} />
            <skinnedMesh name="ParrotFish_3" geometry={nodes.ParrotFish_3.geometry} material={materials.ParrotFish_Main} skeleton={nodes.ParrotFish_3.skeleton} />
            <skinnedMesh name="ParrotFish_4" geometry={nodes.ParrotFish_4.geometry} material={materials.ParrotFish_Teeth} skeleton={nodes.ParrotFish_4.skeleton} />
            <skinnedMesh name="ParrotFish_5" geometry={nodes.ParrotFish_5.geometry} material={materials.Eyes} skeleton={nodes.ParrotFish_5.skeleton} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/ParrotFish.glb')
