/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Shark_1: THREE.SkinnedMesh
    Shark_2: THREE.SkinnedMesh
    Shark_3: THREE.SkinnedMesh
    Shark_4: THREE.SkinnedMesh
    Main1: THREE.Bone
  }
  materials: {
    Shark_Dark: THREE.MeshStandardMaterial
    Shark_Light: THREE.MeshStandardMaterial
    Shark_Main: THREE.MeshStandardMaterial
    Eyes: THREE.MeshStandardMaterial
  }
}

type ActionName = 'Fish_Armature|Attack' | 'Fish_Armature|Death' | 'Fish_Armature|Out_Of_Water' | 'Fish_Armature|Swimming_Fast' | 'Fish_Armature|Swimming_Impulse' | 'Fish_Armature|Swimming_Normal'
type GLTFActions = Record<ActionName, THREE.AnimationAction>

export function Model(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials, animations } = useGLTF('/Shark.glb') as GLTFResult
  const { actions } = useAnimations<GLTFActions>(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Root_Scene">
        <group name="RootNode">
          <group name="Fish_Armature" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <primitive object={nodes.Main1} />
          </group>
          <group name="Shark" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <skinnedMesh name="Shark_1" geometry={nodes.Shark_1.geometry} material={materials.Shark_Dark} skeleton={nodes.Shark_1.skeleton} />
            <skinnedMesh name="Shark_2" geometry={nodes.Shark_2.geometry} material={materials.Shark_Light} skeleton={nodes.Shark_2.skeleton} />
            <skinnedMesh name="Shark_3" geometry={nodes.Shark_3.geometry} material={materials.Shark_Main} skeleton={nodes.Shark_3.skeleton} />
            <skinnedMesh name="Shark_4" geometry={nodes.Shark_4.geometry} material={materials.Eyes} skeleton={nodes.Shark_4.skeleton} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Shark.glb')
