/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Worm_1: THREE.Mesh
    Worm_2: THREE.Mesh
  }
  materials: {
    Worm: THREE.MeshStandardMaterial
    Black: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/Worm.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={209.45}>
        <mesh geometry={nodes.Worm_1.geometry} material={materials.Worm} />
        <mesh geometry={nodes.Worm_2.geometry} material={materials.Black} />
      </group>
    </group>
  )
}

useGLTF.preload('/Worm.glb')
