/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useAnimationsWithCleanup } from '@/hooks/useAnimationsWithCleanup'
import { GenericAnimationController } from '@/components/canvas/GenericAnimationController'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    ZebraClownfish_1: THREE.SkinnedMesh
    ZebraClownfish_2: THREE.SkinnedMesh
    ZebraClownfish_3: THREE.SkinnedMesh
    Main1: THREE.Bone
  }
  materials: {
    ZebraClownFish_Main: THREE.MeshStandardMaterial
    ZebraClownFish_Light: THREE.MeshStandardMaterial
    Eyes: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

type ActionName =
  | 'Fish_Armature|Attack'
  | 'Fish_Armature|Death'
  | 'Fish_Armature|Out_Of_Water'
  | 'Fish_Armature|Swimming_Fast'
  | 'Fish_Armature|Swimming_Impulse'
  | 'Fish_Armature|Swimming_Normal'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials, animations } = useGLTF('/glb/cute_fish_pack/ZebraClownFish.glb') as unknown as GLTFResult
  const { actions } = useAnimationsWithCleanup(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <GenericAnimationController actions={actions} />
      <group name='Root_Scene'>
        <group name='RootNode'>
          <group name='Fish_Armature' rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <primitive object={nodes.Main1} />
          </group>
          <group name='ZebraClownfish' rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <skinnedMesh
              name='ZebraClownfish_1'
              geometry={nodes.ZebraClownfish_1.geometry}
              material={materials.ZebraClownFish_Main}
              skeleton={nodes.ZebraClownfish_1.skeleton}
            />
            <skinnedMesh
              name='ZebraClownfish_2'
              geometry={nodes.ZebraClownfish_2.geometry}
              material={materials.ZebraClownFish_Light}
              skeleton={nodes.ZebraClownfish_2.skeleton}
            />
            <skinnedMesh
              name='ZebraClownfish_3'
              geometry={nodes.ZebraClownfish_3.geometry}
              material={materials.Eyes}
              skeleton={nodes.ZebraClownfish_3.skeleton}
            />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/glb/cute_fish_pack/ZebraClownFish.glb')
