/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Arrow_Up_1: THREE.Mesh
    Arrow_Up_2: THREE.Mesh
  }
  materials: {
    Wood: THREE.MeshStandardMaterial
    Main_Dark: THREE.MeshStandardMaterial
  }
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/glb/platformer_game_pack/Arrow_Up.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Arrow_Up_1.geometry} material={materials.Wood} />
        <mesh geometry={nodes.Arrow_Up_2.geometry} material={materials.Main_Dark} />
      </group>
    </group>
  )
}

useGLTF.preload('/glb/platformer_game_pack/Arrow_Up.glb')
