/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Bouncer_1: THREE.SkinnedMesh
    Bouncer_2: THREE.SkinnedMesh
    Root: THREE.Bone
  }
  materials: {
    Metal: THREE.MeshStandardMaterial
    Red: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

type ActionName = 'Bouncer_Bounce' | 'Bouncer_Idle' | 'BouncerArmature|Bouncer_Bounce' | 'BouncerArmature|Bouncer_Idle'
interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials, animations } = useGLTF('/glb/platformer_game_pack/Bouncer.glb') as unknown as GLTFResult
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name='Root_Scene'>
        <group name='RootNode'>
          <group name='BouncerArmature' rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <primitive object={nodes.Root} />
          </group>
          <group name='Bouncer' rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <skinnedMesh
              name='Bouncer_1'
              geometry={nodes.Bouncer_1.geometry}
              material={materials.Metal}
              skeleton={nodes.Bouncer_1.skeleton}
            />
            <skinnedMesh
              name='Bouncer_2'
              geometry={nodes.Bouncer_2.geometry}
              material={materials.Red}
              skeleton={nodes.Bouncer_2.skeleton}
            />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/glb/platformer_game_pack/Bouncer.glb')
