/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Fence_Middle_1: THREE.Mesh
    Fence_Middle_2: THREE.Mesh
  }
  materials: {
    Wood_Light: THREE.MeshStandardMaterial
    Wood: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/Fence_Middle.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.Fence_Middle_1.geometry} material={materials.Wood_Light} />
        <mesh geometry={nodes.Fence_Middle_2.geometry} material={materials.Wood} />
      </group>
    </group>
  )
}

useGLTF.preload('/Fence_Middle.glb')
