/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import type * as THREE from "three";
import type { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Fruit_1: THREE.Mesh;
    Fruit_2: THREE.Mesh;
  };
  materials: {
    Red: THREE.MeshStandardMaterial;
    Green_Light: THREE.MeshStandardMaterial;
  };
};

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/glb/platformer_game_pack/Fruit.glb",
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.Fruit_1.geometry} material={materials.Red} />
        <mesh geometry={nodes.Fruit_2.geometry} material={materials.Green_Light} />
      </group>
    </group>
  );
}

useGLTF.preload("/glb/platformer_game_pack/Fruit.glb");
