/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    SpikyBall_1: THREE.Mesh
    SpikyBall_2: THREE.Mesh
    SpikyBall_3: THREE.Mesh
  }
  materials: {
    Black: THREE.MeshStandardMaterial
    DarkMetal: THREE.MeshStandardMaterial
    Metal: THREE.MeshStandardMaterial
  }
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/glb/platformer_game_pack/SpikyBall.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.SpikyBall_1.geometry} material={materials.Black} />
        <mesh geometry={nodes.SpikyBall_2.geometry} material={materials.DarkMetal} />
        <mesh geometry={nodes.SpikyBall_3.geometry} material={materials.Metal} />
      </group>
    </group>
  )
}

useGLTF.preload('/glb/platformer_game_pack/SpikyBall.glb')
