/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import type * as THREE from "three";
import type { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Stairs_1: THREE.Mesh;
    Stairs_2: THREE.Mesh;
  };
  materials: {
    Wood: THREE.MeshStandardMaterial;
    Wood_Light: THREE.MeshStandardMaterial;
  };
};

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/glb/platformer_game_pack/Stairs.glb",
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={8.51}>
        <mesh geometry={nodes.Stairs_1.geometry} material={materials.Wood} />
        <mesh geometry={nodes.Stairs_2.geometry} material={materials.Wood_Light} />
      </group>
    </group>
  );
}

useGLTF.preload("/glb/platformer_game_pack/Stairs.glb");
