/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import type * as THREE from "three";
import type { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Tree_1: THREE.Mesh;
    Tree_2: THREE.Mesh;
  };
  materials: {
    Wood: THREE.MeshStandardMaterial;
    Green: THREE.MeshStandardMaterial;
  };
};

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/glb/platformer_game_pack/Tree.glb",
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.Tree_1.geometry} material={materials.Wood} />
        <mesh geometry={nodes.Tree_2.geometry} material={materials.Green} />
      </group>
    </group>
  );
}

useGLTF.preload("/glb/platformer_game_pack/Tree.glb");
