/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Flag_1: THREE.Mesh
    Flag_2: THREE.Mesh
  }
  materials: {
    Brown: THREE.MeshStandardMaterial
    LightRed: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/Flag.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.Flag_1.geometry} material={materials.Brown} />
        <mesh geometry={nodes.Flag_2.geometry} material={materials.LightRed} />
      </group>
    </group>
  )
}

useGLTF.preload('/Flag.glb')
