/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Raft_Paddle_1: THREE.Mesh
    Raft_Paddle_2: THREE.Mesh
  }
  materials: {
    Blue: THREE.MeshStandardMaterial
    BrightYellow: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/Raft_Paddle.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={198.94}>
        <mesh geometry={nodes.Raft_Paddle_1.geometry} material={materials.Blue} />
        <mesh geometry={nodes.Raft_Paddle_2.geometry} material={materials.BrightYellow} />
      </group>
    </group>
  )
}

useGLTF.preload('/Raft_Paddle.glb')
