/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import type * as THREE from "three";
import type { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Raft_1: THREE.Mesh;
    Raft_2: THREE.Mesh;
  };
  materials: {
    BrightYellow: THREE.MeshStandardMaterial;
    Black: THREE.MeshStandardMaterial;
  };
};

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/glb/survival_pack/Raft.glb") as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.Raft_1.geometry} material={materials.BrightYellow} />
        <mesh geometry={nodes.Raft_2.geometry} material={materials.Black} />
      </group>
    </group>
  );
}

useGLTF.preload("/glb/survival_pack/Raft.glb");
