/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Shotgun_ShortStock_1: THREE.Mesh
    Shotgun_ShortStock_2: THREE.Mesh
    Shotgun_ShortStock_3: THREE.Mesh
    Shotgun_ShortStock_4: THREE.Mesh
  }
  materials: {
    Metal: THREE.MeshStandardMaterial
    Black: THREE.MeshStandardMaterial
    Wood: THREE.MeshStandardMaterial
    DarkMetal: THREE.MeshStandardMaterial
  }
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/glb/survival_pack/Shotgun_ShortStock.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.Shotgun_ShortStock_1.geometry} material={materials.Metal} />
        <mesh geometry={nodes.Shotgun_ShortStock_2.geometry} material={materials.Black} />
        <mesh geometry={nodes.Shotgun_ShortStock_3.geometry} material={materials.Wood} />
        <mesh geometry={nodes.Shotgun_ShortStock_4.geometry} material={materials.DarkMetal} />
      </group>
    </group>
  )
}

useGLTF.preload('/glb/survival_pack/Shotgun_ShortStock.glb')
