/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Torch_1: THREE.Mesh
    Torch_2: THREE.Mesh
    Torch_3: THREE.Mesh
    Torch_4: THREE.Mesh
  }
  materials: {
    Yellow: THREE.MeshStandardMaterial
    Black: THREE.MeshStandardMaterial
    LightBlue: THREE.MeshStandardMaterial
    DarkYellow: THREE.MeshStandardMaterial
  }
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/glb/survival_pack/Torch.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={198.94}>
        <mesh geometry={nodes.Torch_1.geometry} material={materials.Yellow} />
        <mesh geometry={nodes.Torch_2.geometry} material={materials.Black} />
        <mesh geometry={nodes.Torch_3.geometry} material={materials.LightBlue} />
        <mesh geometry={nodes.Torch_4.geometry} material={materials.DarkYellow} />
      </group>
    </group>
  )
}

useGLTF.preload('/glb/survival_pack/Torch.glb')
