/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Trashcan_1: THREE.Mesh
    Trashcan_2: THREE.Mesh
  }
  materials: {
    DarkGreen: THREE.MeshStandardMaterial
    Black: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/glb/Trashcan.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={156.88}>
        <mesh geometry={nodes.Trashcan_1.geometry} material={materials.DarkGreen} />
        <mesh geometry={nodes.Trashcan_2.geometry} material={materials.Black} />
      </group>
    </group>
  )
}

useGLTF.preload('/Trashcan.glb')
