/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import type * as THREE from "three";
import type { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    WoodLog_1: THREE.Mesh;
    WoodLog_2: THREE.Mesh;
  };
  materials: {
    Wood: THREE.MeshStandardMaterial;
    LightWood: THREE.MeshStandardMaterial;
  };
};

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/glb/survival_pack/WoodLog.glb") as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, -0.67]} scale={198.94}>
        <mesh geometry={nodes.WoodLog_1.geometry} material={materials.Wood} />
        <mesh geometry={nodes.WoodLog_2.geometry} material={materials.LightWood} />
      </group>
    </group>
  );
}

useGLTF.preload("/glb/survival_pack/WoodLog.glb");
