/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Bed_Bunk_1: THREE.Mesh
    Bed_Bunk_2: THREE.Mesh
    Bed_Bunk_3: THREE.Mesh
    Bed_Bunk_4: THREE.Mesh
  }
  materials: {
    Wood: THREE.MeshStandardMaterial
    Grey: THREE.MeshStandardMaterial
    Red: THREE.MeshStandardMaterial
    White: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/glb/Bed_Bunk.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.Bed_Bunk_1.geometry} material={materials.Wood} />
        <mesh geometry={nodes.Bed_Bunk_2.geometry} material={materials.Grey} />
        <mesh geometry={nodes.Bed_Bunk_3.geometry} material={materials.Red} />
        <mesh geometry={nodes.Bed_Bunk_4.geometry} material={materials.White} />
      </group>
    </group>
  )
}

useGLTF.preload('/Bed_Bunk.glb')
