/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Carpet_1_1: THREE.Mesh
    Carpet_1_2: THREE.Mesh
  }
  materials: {
    DarkRed: THREE.MeshStandardMaterial
    LightOrange: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/glb/Carpet_1.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.Carpet_1_1.geometry} material={materials.DarkRed} />
        <mesh geometry={nodes.Carpet_1_2.geometry} material={materials.LightOrange} />
      </group>
    </group>
  )
}

useGLTF.preload('/Carpet_1.glb')
