/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Door_5_1: THREE.Mesh
    Door_5_2: THREE.Mesh
  }
  materials: {
    Wood: THREE.MeshStandardMaterial
    Metal: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/Door_5.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.Door_5_1.geometry} material={materials.Wood} />
        <mesh geometry={nodes.Door_5_2.geometry} material={materials.Metal} />
      </group>
    </group>
  )
}

useGLTF.preload('/Door_5.glb')
