/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import type * as THREE from "three";
import type { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Kitchen_Fridge_1: THREE.Mesh;
    Kitchen_Fridge_2: THREE.Mesh;
  };
  materials: {
    White: THREE.MeshStandardMaterial;
    Black: THREE.MeshStandardMaterial;
  };
};

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/glb/house_interior_pack/Kitchen_Fridge.glb",
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.Kitchen_Fridge_1.geometry} material={materials.White} />
        <mesh geometry={nodes.Kitchen_Fridge_2.geometry} material={materials.Black} />
      </group>
    </group>
  );
}

useGLTF.preload("/glb/house_interior_pack/Kitchen_Fridge.glb");
