/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import type * as THREE from "three";
import type { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    NightStand_3_1: THREE.Mesh;
    NightStand_3_2: THREE.Mesh;
  };
  materials: {
    Wood: THREE.MeshStandardMaterial;
    Metal: THREE.MeshStandardMaterial;
  };
};

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/glb/house_interior_pack/NightStand_3.glb",
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.NightStand_3_1.geometry} material={materials.Wood} />
        <mesh geometry={nodes.NightStand_3_2.geometry} material={materials.Metal} />
      </group>
    </group>
  );
}

useGLTF.preload("/glb/house_interior_pack/NightStand_3.glb");
