/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import type * as THREE from "three";
import type { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Lootbox_Base_1: THREE.Mesh;
    Lootbox_Base_2: THREE.Mesh;
    Lootbox_Top_1: THREE.Mesh;
    Lootbox_Top_2: THREE.Mesh;
  };
  materials: {
    DarkGrey: THREE.MeshStandardMaterial;
    Grey: THREE.MeshStandardMaterial;
    Orange: THREE.MeshStandardMaterial;
  };
};

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/glb/cyberpunk_pack/Lootbox.glb") as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.Lootbox_Base_1.geometry} material={materials.DarkGrey} />
        <mesh geometry={nodes.Lootbox_Base_2.geometry} material={materials.Grey} />
      </group>
      <group position={[0, 0.4, -0.29]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.Lootbox_Top_1.geometry} material={materials.Grey} />
        <mesh geometry={nodes.Lootbox_Top_2.geometry} material={materials.Orange} />
      </group>
    </group>
  );
}

useGLTF.preload("/glb/cyberpunk_pack/Lootbox.glb");
