/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Pickup_Heart_1: THREE.Mesh
    Pickup_Heart_2: THREE.Mesh
  }
  materials: {
    LightGrey: THREE.MeshStandardMaterial
    Red: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/glb/Pickup_Heart.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.Pickup_Heart_1.geometry} material={materials.LightGrey} />
        <mesh geometry={nodes.Pickup_Heart_2.geometry} material={materials.Red} />
      </group>
    </group>
  )
}

useGLTF.preload('/Pickup_Heart.glb')
