/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Support_1: THREE.Mesh
    Support_2: THREE.Mesh
  }
  materials: {
    MetalLight: THREE.MeshStandardMaterial
    Grey: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/Support.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.Support_1.geometry} material={materials.MetalLight} />
        <mesh geometry={nodes.Support_2.geometry} material={materials.Grey} />
      </group>
    </group>
  )
}

useGLTF.preload('/Support.glb')
