/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Tank_1: THREE.Mesh
    Tank_2: THREE.Mesh
    Tank_3: THREE.Mesh
  }
  materials: {
    LightGrey: THREE.MeshStandardMaterial
    Orange: THREE.MeshStandardMaterial
    Black: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/Tank.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.Tank_1.geometry} material={materials.LightGrey} />
        <mesh geometry={nodes.Tank_2.geometry} material={materials.Orange} />
        <mesh geometry={nodes.Tank_3.geometry} material={materials.Black} />
      </group>
    </group>
  )
}

useGLTF.preload('/Tank.glb')
