/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Turret_Teleporter_1: THREE.Mesh
    Turret_Teleporter_2: THREE.Mesh
    Turret_Teleporter_3: THREE.Mesh
    Turret_Teleporter_4: THREE.Mesh
  }
  materials: {
    Black: THREE.MeshStandardMaterial
    Orange: THREE.MeshStandardMaterial
    LightGrey: THREE.MeshStandardMaterial
    Grey: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/glb/Turret_Teleporter.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.Turret_Teleporter_1.geometry} material={materials.Black} />
        <mesh geometry={nodes.Turret_Teleporter_2.geometry} material={materials.Orange} />
        <mesh geometry={nodes.Turret_Teleporter_3.geometry} material={materials.LightGrey} />
        <mesh geometry={nodes.Turret_Teleporter_4.geometry} material={materials.Grey} />
      </group>
    </group>
  )
}

useGLTF.preload('/Turret_Teleporter.glb')
